### ISSUE TITLE
Why do you use string for numeric representation?

### ISSUE THREAD

**Issue by mr-tron** [ferdypruis/iso3166#1]

**Comment by ferdypruis** [comment]
Hi @mr-tron,

I use a string because the ISO 3166-1 numeric codes always consist of three digits, optionally with leading zero's.
The length of 3 is significant and impossible to enforce with a number type, but a leading zero is as much part of the value as every other digit, it's not just formatting.

Just because it consist of numerical values does not mean it must be stored in a number type. Same goes for example for phone numbers and postal codes. There is no arithmetic value.

**Comment by mr-tron** [comment]
Adding leading zeroes is simple task on representation level. Something like `fmt.Sprintf("%03d", numericCountryID)`

**Comment by mr-tron** [comment]
Or changing methods
```
// Numeric returns the ISO 3166-1 numeric code.
func (c Country) Numeric() int { return countries[c].numeric }

// NumericString returns three-digit text representation of the ISO 3166-1 numeric code
func (c Country) NumericString() string { return fmt.Sprintf("%03d", countries[c].numeric) }
```

**Comment by ferdypruis** [comment]
The leading zero is not a matter of representation. The zero is part of the value.
It makes no sense to me to treat it as a number. Why would you prefer this? Would you use integers for postal codes and bank account numbers?

If you really want it as a number, this is also a simple task. 
Something like `numericCountryID, _ := strconv.Atoi(iso3166.RU.Numeric())`
